### ISSUE TITLE
URL rewrite errors 

### ISSUE THREAD

**Issue by cyberdelia** [jezdez/django-staticfiles#20] opened 2011-12-15 08:54 UTC
URL rewriting in css, fail on many common case use in css like ie hack like :

```
url(web-font.eot?#iefix)
```

And SVG id in url :

```
url(web-font.svg#webfontIyfZbseF)
```

And also try to rewrite data-uri :

```
url(data:font/woff;charset=utf-8;base64,d09GRgABAAAAADJoAA0AAAAAR2QAAQAAAAAAAAAAAAA)
```

And it's a common pratice used for cross-platform web-fonts support.

**Comment by jezdez** [comment] 2011-12-15 10:17
This is basically a dupe of #18.

**Closed as completed by jezdez** 2011-12-15 10:17 UTC
